// Auto-generated by generate-backend.js
module.exports = (sequelize, DataTypes) => {
  const Beiratkozas = sequelize.define("beiratkozas", {
    "hallgato_id": {
  type: DataTypes.INTEGER,
  primaryKey: true,
  allowNull: false,
},
"kurzus_id": {
  type: DataTypes.INTEGER,
  primaryKey: true,
  allowNull: false,
},
"felvet_datum": {
  type: DataTypes.DATE,
  allowNull: false,
  defaultValue: DataTypes.NOW,
},
"jegy": {
  type: DataTypes.SMALLINT,
}
  }, {
    tableName: "beiratkozas",
    timestamps: false,
    indexes: [
      { name: "ix_beiratkozas_kurzus", fields: ["kurzus_id"] }
    ]
  });

  Beiratkozas.associate = (models) => {
    // FK fk_beiratkozas_hallgato (hallgato_id -> hallgato.id)
if (models["hallgato"]) {
  models["beiratkozas"].belongsTo(models["hallgato"], {
    as: "hallgato",
    foreignKey: "hallgato_id",
    targetKey: "id"
  });
  models["hallgato"].hasMany(models["beiratkozas"], {
    as: "beiratkozasList",
    foreignKey: "hallgato_id",
    sourceKey: "id"
  });
}

// FK fk_beiratkozas_kurzus (kurzus_id -> kurzus.id)
if (models["kurzus"]) {
  models["beiratkozas"].belongsTo(models["kurzus"], {
    as: "kurzus",
    foreignKey: "kurzus_id",
    targetKey: "id"
  });
  models["kurzus"].hasMany(models["beiratkozas"], {
    as: "beiratkozasList",
    foreignKey: "kurzus_id",
    sourceKey: "id"
  });
}
  };

  return Beiratkozas;
};