// Auto-generated by generate-backend.js
module.exports = (sequelize, DataTypes) => {
  const Beiratkozas = sequelize.define('beiratkozas', {
    hallgato_id: {
  type: DataTypes.INTEGER,
  primaryKey: true,
},
kurzus_id: {
  type: DataTypes.INTEGER,
  primaryKey: true,
},
felvet_datum: {
  type: DataTypes.DATE,
  defaultValue: "current_timestamp()",
},
jegy: {
  type: DataTypes.SMALLINT,
}
  }, {
    tableName: 'beiratkozas',
    timestamps: false, indexes: [
      { name: "ix_beiratkozas_kurzus", fields: ["kurzus_id"] }
    ]
  });

  Beiratkozas.associate = (models) => {
    // FK fk_beiratkozas_hallgato (hallgato_id -> hallgato.id)
models['beiratkozas'].belongsTo(models['hallgato'], {
  as: 'hallgato',
  foreignKey: 'hallgato_id'
});
models['hallgato'].hasMany(models['beiratkozas'], {
  as: 'beiratkozasList',
  foreignKey: 'hallgato_id'
});

// FK fk_beiratkozas_kurzus (kurzus_id -> kurzus.id)
models['beiratkozas'].belongsTo(models['kurzus'], {
  as: 'kurzus',
  foreignKey: 'kurzus_id'
});
models['kurzus'].hasMany(models['beiratkozas'], {
  as: 'beiratkozasList',
  foreignKey: 'kurzus_id'
});
  };

  return Beiratkozas;
};