// Auto-generated by generate-backend.js
module.exports = (sequelize, DataTypes) => {
  const Hallgato = sequelize.define('hallgato', {
    id: {
  type: DataTypes.INTEGER,
  primaryKey: true,
  autoIncrement: true,
  allowNull: false,
},
nev: {
  type: DataTypes.STRING,
  allowNull: false,
},
email: {
  type: DataTypes.STRING,
  allowNull: false,
},
szak: {
  type: DataTypes.STRING,
  allowNull: false,
},
aktiv: {
  type: DataTypes.BOOLEAN,
  allowNull: false,
  defaultValue: 1,
},
felvetel_eve: {
  type: DataTypes.INTEGER,
  allowNull: false,
}
  }, {
    tableName: 'hallgato',
    timestamps: false
  });

  Hallgato.associate = (models) => {
    // nincsenek FK-k
  };

  return Hallgato;
};