// Auto-generated by generate-backend.js
module.exports = (sequelize, DataTypes) => {
  const Hallgato = sequelize.define("hallgato", {
    "id": {
  type: DataTypes.INTEGER,
  primaryKey: true,
  autoIncrement: true,
  allowNull: false,
},
"neptun": {
  type: DataTypes.STRING,
  allowNull: false,
},
"nev": {
  type: DataTypes.STRING,
  allowNull: false,
},
"nem": {
  type: DataTypes.ENUM('no', 'ferfi', 'egyeb'),
},
"szak": {
  type: DataTypes.STRING,
  allowNull: false,
},
"evfolyam": {
  type: DataTypes.SMALLINT,
  allowNull: false,
},
"szuldatum": {
  type: DataTypes.DATEONLY,
},
"email": {
  type: DataTypes.STRING,
}
  }, {
    tableName: "hallgato",
    timestamps: false,
    indexes: [
      { name: "neptun", unique: true, fields: ["neptun"] },
      { name: "uq_hallgato_email", unique: true, fields: ["email"] }
    ]
  });

  Hallgato.associate = (models) => {
    // nincsenek FK-k
  };

  return Hallgato;
};