// Auto-generated by generate-backend.js
module.exports = (sequelize, DataTypes) => {
  const Hallgato = sequelize.define('hallgato', {
    id: {
  type: DataTypes.INTEGER,
  primaryKey: true,
},
neptun: {
  type: DataTypes.STRING(6),
},
nev: {
  type: DataTypes.STRING(120),
},
nem: {
  type: DataTypes.ENUM('no', 'ferfi', 'egyeb'),
},
szak: {
  type: DataTypes.STRING(80),
},
evfolyam: {
  type: DataTypes.SMALLINT,
},
szuldatum: {
  type: DataTypes.DATEONLY,
},
email: {
  type: DataTypes.STRING(120),
}
  }, {
    tableName: 'hallgato',
    timestamps: false
  });

  Hallgato.associate = (models) => {
    // nincsenek FK-k
  };

  return Hallgato;
};