// Auto-generated by generate-backend.js
module.exports = (sequelize, DataTypes) => {
  const Jelentkezes = sequelize.define('jelentkezes', {
    hallgato_id: {
  type: DataTypes.INTEGER,
  primaryKey: true,
  allowNull: false,
},
kurzus_id: {
  type: DataTypes.INTEGER,
  primaryKey: true,
  allowNull: false,
},
jelentkezes_datuma: {
  type: DataTypes.DATEONLY,
  allowNull: false,
},
allapot: {
  type: DataTypes.ENUM('aktiv', 'teljesitett', 'lemondott'),
  allowNull: false,
  defaultValue: 'aktiv',
},
jegy: {
  type: DataTypes.INTEGER,
}
  }, {
    tableName: 'jelentkezes',
    timestamps: false
  }
  ,{
    indexes: [
      { name: "idx_jelentkezes_kurzus", fields: ["kurzus_id"] }
    ]
  });

  Jelentkezes.associate = (models) => {
    // FK fk_jelentkezes_hallgato (hallgato_id -> hallgato.id)
models['jelentkezes'].belongsTo(models['hallgato'], {
  as: 'hallgato',
  foreignKey: 'hallgato_id'
});
models['hallgato'].hasMany(models['jelentkezes'], {
  as: 'jelentkezesList',
  foreignKey: 'hallgato_id'
});

// FK fk_jelentkezes_kurzus (kurzus_id -> kurzus.id)
models['jelentkezes'].belongsTo(models['kurzus'], {
  as: 'kurzus',
  foreignKey: 'kurzus_id'
});
models['kurzus'].hasMany(models['jelentkezes'], {
  as: 'jelentkezesList',
  foreignKey: 'kurzus_id'
});
  };

  return Jelentkezes;
};