// Auto-generated by generate-backend.js
module.exports = (sequelize, DataTypes) => {
  const Kurzus = sequelize.define('kurzus', {
    id: {
  type: DataTypes.INTEGER,
  primaryKey: true,
},
tantargy_id: {
  type: DataTypes.INTEGER,
},
tanar_id: {
  type: DataTypes.INTEGER,
},
felev: {
  type: DataTypes.STRING(16),
},
tipus: {
  type: DataTypes.ENUM('eloadas', 'gyakorlat', 'labor'),
  defaultValue: "eloadas",
},
kapacitas: {
  type: DataTypes.SMALLINT,
  defaultValue: 100,
},
terem: {
  type: DataTypes.STRING(32),
}
  }, {
    tableName: 'kurzus',
    timestamps: false, indexes: [
      { name: "ix_kurzus_tantargy", fields: ["tantargy_id"] },
      { name: "ix_kurzus_tanar", fields: ["tanar_id"] }
    ]
  });

  Kurzus.associate = (models) => {
    // FK fk_kurzus_tanar (tanar_id -> tanar.id)
models['kurzus'].belongsTo(models['tanar'], {
  as: 'tanar',
  foreignKey: 'tanar_id'
});
models['tanar'].hasMany(models['kurzus'], {
  as: 'kurzusList',
  foreignKey: 'tanar_id'
});

// FK fk_kurzus_tantargy (tantargy_id -> tantargy.id)
models['kurzus'].belongsTo(models['tantargy'], {
  as: 'tantargy',
  foreignKey: 'tantargy_id'
});
models['tantargy'].hasMany(models['kurzus'], {
  as: 'kurzusList',
  foreignKey: 'tantargy_id'
});
  };

  return Kurzus;
};