// Auto-generated by generate-backend.js
module.exports = (sequelize, DataTypes) => {
  const Kurzus = sequelize.define('kurzus', {
    id: {
  type: DataTypes.INTEGER,
  primaryKey: true,
  autoIncrement: true,
  allowNull: false,
},
oktato_id: {
  type: DataTypes.INTEGER,
  allowNull: false,
},
kod: {
  type: DataTypes.STRING,
  allowNull: false,
},
nev: {
  type: DataTypes.STRING,
  allowNull: false,
},
felev: {
  type: DataTypes.STRING,
  allowNull: false,
},
kredit: {
  type: DataTypes.INTEGER,
  allowNull: false,
  defaultValue: 5,
},
tipus: {
  type: DataTypes.ENUM('eloadas', 'gyakorlat', 'labor'),
  allowNull: false,
  defaultValue: 'eloadas',
},
max_letszam: {
  type: DataTypes.INTEGER,
  allowNull: false,
  defaultValue: 30,
}
  }, {
    tableName: 'kurzus',
    timestamps: false
  }
  ,{
    indexes: [
      { name: "idx_kurzus_oktato", fields: ["oktato_id"] }
    ]
  });

  Kurzus.associate = (models) => {
    // FK fk_kurzus_oktato (oktato_id -> oktato.id)
models['kurzus'].belongsTo(models['oktato'], {
  as: 'oktato',
  foreignKey: 'oktato_id'
});
models['oktato'].hasMany(models['kurzus'], {
  as: 'kurzusList',
  foreignKey: 'oktato_id'
});
  };

  return Kurzus;
};