// Auto-generated by generate-backend.js
module.exports = (sequelize, DataTypes) => {
  const Kurzus = sequelize.define("kurzus", {
    "id": {
  type: DataTypes.INTEGER,
  primaryKey: true,
  autoIncrement: true,
  allowNull: false,
},
"tantargy_id": {
  type: DataTypes.INTEGER,
  allowNull: false,
},
"tanar_id": {
  type: DataTypes.INTEGER,
  allowNull: false,
},
"felev": {
  type: DataTypes.STRING,
  allowNull: false,
},
"tipus": {
  type: DataTypes.ENUM('eloadas', 'gyakorlat', 'labor'),
  allowNull: false,
  defaultValue: 'eloadas',
},
"kapacitas": {
  type: DataTypes.SMALLINT,
  defaultValue: 100,
},
"terem": {
  type: DataTypes.STRING,
}
  }, {
    tableName: "kurzus",
    timestamps: false,
    indexes: [
      { name: "ix_kurzus_tantargy", fields: ["tantargy_id"] },
      { name: "ix_kurzus_tanar", fields: ["tanar_id"] }
    ]
  });

  Kurzus.associate = (models) => {
    // FK fk_kurzus_tanar (tanar_id -> tanar.id)
if (models["tanar"]) {
  models["kurzus"].belongsTo(models["tanar"], {
    as: "tanar",
    foreignKey: "tanar_id",
    targetKey: "id"
  });
  models["tanar"].hasMany(models["kurzus"], {
    as: "kurzusList",
    foreignKey: "tanar_id",
    sourceKey: "id"
  });
}

// FK fk_kurzus_tantargy (tantargy_id -> tantargy.id)
if (models["tantargy"]) {
  models["kurzus"].belongsTo(models["tantargy"], {
    as: "tantargy",
    foreignKey: "tantargy_id",
    targetKey: "id"
  });
  models["tantargy"].hasMany(models["kurzus"], {
    as: "kurzusList",
    foreignKey: "tantargy_id",
    sourceKey: "id"
  });
}
  };

  return Kurzus;
};