// Auto-generated by generate-backend.js
module.exports = (sequelize, DataTypes) => {
  const Oktato = sequelize.define('oktato', {
    id: {
  type: DataTypes.INTEGER,
  primaryKey: true,
  autoIncrement: true,
  allowNull: false,
},
nev: {
  type: DataTypes.STRING,
  allowNull: false,
},
tanszek: {
  type: DataTypes.STRING,
  allowNull: false,
},
beosztas: {
  type: DataTypes.ENUM('tanarseged', 'adjunktus', 'docens', 'professzor'),
  allowNull: false,
  defaultValue: 'adjunktus',
}
  }, {
    tableName: 'oktato',
    timestamps: false
  });

  Oktato.associate = (models) => {
    // nincsenek FK-k
  };

  return Oktato;
};