// Auto-generated by generate-backend.js
module.exports = (sequelize, DataTypes) => {
  const Tanar = sequelize.define('tanar', {
    id: {
  type: DataTypes.INTEGER,
  primaryKey: true,
},
nev: {
  type: DataTypes.STRING(120),
},
tanszek: {
  type: DataTypes.STRING(120),
},
email: {
  type: DataTypes.STRING(120),
}
  }, {
    tableName: 'tanar',
    timestamps: false
  });

  Tanar.associate = (models) => {
    // nincsenek FK-k
  };

  return Tanar;
};