// Auto-generated by generate-backend.js
module.exports = (sequelize, DataTypes) => {
  const Tanar = sequelize.define("tanar", {
    "id": {
  type: DataTypes.INTEGER,
  primaryKey: true,
  autoIncrement: true,
  allowNull: false,
},
"nev": {
  type: DataTypes.STRING,
  allowNull: false,
},
"tanszek": {
  type: DataTypes.STRING,
  allowNull: false,
},
"email": {
  type: DataTypes.STRING,
  allowNull: false,
}
  }, {
    tableName: "tanar",
    timestamps: false,
    indexes: [
      { name: "uq_tanar_email", unique: true, fields: ["email"] }
    ]
  });

  Tanar.associate = (models) => {
    // nincsenek FK-k
  };

  return Tanar;
};