// Auto-generated by generate-backend.js
module.exports = (sequelize, DataTypes) => {
  const Tantargy = sequelize.define("tantargy", {
    "id": {
  type: DataTypes.INTEGER,
  primaryKey: true,
  autoIncrement: true,
  allowNull: false,
},
"kod": {
  type: DataTypes.STRING,
  allowNull: false,
},
"nev": {
  type: DataTypes.STRING,
  allowNull: false,
},
"kredit": {
  type: DataTypes.SMALLINT,
  allowNull: false,
},
"aktiv": {
  type: DataTypes.BOOLEAN,
  allowNull: false,
  defaultValue: 1,
}
  }, {
    tableName: "tantargy",
    timestamps: false,
    indexes: [
      { name: "uq_tantargy_kod", unique: true, fields: ["kod"] }
    ]
  });

  Tantargy.associate = (models) => {
    // nincsenek FK-k
  };

  return Tantargy;
};