// Auto-generated by generate-backend.js
module.exports = (sequelize, DataTypes) => {
  const Tantargy = sequelize.define('tantargy', {
    id: {
  type: DataTypes.INTEGER,
  primaryKey: true,
},
kod: {
  type: DataTypes.STRING(16),
},
nev: {
  type: DataTypes.STRING(160),
},
kredit: {
  type: DataTypes.SMALLINT,
},
aktiv: {
  type: DataTypes.BOOLEAN,
  defaultValue: 1,
}
  }, {
    tableName: 'tantargy',
    timestamps: false
  });

  Tantargy.associate = (models) => {
    // nincsenek FK-k
  };

  return Tantargy;
};